language: python
# cache package wheels (1 cache per python version)
cache: pip
# newer python versions are available only on xenial (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required

jobs:
  include:
  - name: "run test suite with python 3.6"
    python: 3.6
    script: |
      set -e
      export PYTHONPATH=`pwd`/external/mypy
      pytest
  - name: "run test suite with python 3.7"
    python: 3.7
    script: |
      set -e
      export PYTHONPATH=`pwd`/external/mypy
      pytest
  - name: "run direct typecheck" |
      mkdir tmpd
      cp -r sqlalchemy-stubs tmpd/sqlalchemy
      cd tmpd
      python3 -m mypy -p sqlalchemy
      cd ..
      rm -rf tmpd
  - name: "run flake8 on stubs"
    python: 3.6
    script: |
      flake8 sqlalchemy-stubs


before_install: |
  # Upgrade pip, setuptools, and wheel
  pip install -U pip setuptools wheel

install: |
  pip install -r external/mypy/test-requirements.txt
  pip install -U .
  python2 -m pip install --user -U .
